Spring 1
RuslanIbIsh/springprev pull request #1
Opened 2021-02-08 19:52 UTC by RuslanIbIsh

2021-02-08 20:07 UTC, Ilya-brinchuk approved these changes

2021-02-09 07:46 UTC, Sofasmile requested changes

2021-02-09 07:46 UTC, Sofasmile commented on src/main/java/com/iri/spring/dao/impl/UserDaoImpl.java
> +@Primary
do we need this annotation here

2021-02-09 07:46 UTC, Sofasmile commented on src/main/java/com/iri/spring/dao/impl/UserDaoImpl.java
> +    private SessionFactory sessionFactory;
https://mate-academy.github.io/jv-program-fulltime/04_spring/checklist/hw_01.html
> What is better: setter, constructor, or field injection? Think why.

2021-02-09 07:46 UTC, Sofasmile commented on src/main/java/com/iri/spring/service/impl/UserServiceImpl.java
> +    public UserServiceImpl(@Qualifier(value = "userDaoImpl") UserDao userDao) {
do we need Qualifier here?

2021-02-09 07:46 UTC, Sofasmile commented on src/main/java/com/iri/spring/service/impl/UserServiceImpl.java
> +    private UserDao userDao;
```suggestion
    private final UserDao userDao;
```

2021-02-09 08:15 UTC, AntonPanchishko approved these changes

2021-02-09 09:36 UTC, RuslanIbIsh commented on src/main/java/com/iri/spring/dao/impl/UserDaoImpl.java
> +@Primary
just for remember

2021-02-09 09:39 UTC, RuslanIbIsh commented on src/main/java/com/iri/spring/dao/impl/UserDaoImpl.java
> +    private SessionFactory sessionFactory;
throw Constructor app does not run if smth
throw the field = NPE

2021-02-09 09:40 UTC, RuslanIbIsh commented on src/main/java/com/iri/spring/service/impl/UserServiceImpl.java
> +    public UserServiceImpl(@Qualifier(value = "userDaoImpl") UserDao userDao) {
Just for remember

2021-02-09 09:41 UTC, RuslanIbIsh commented on src/main/java/com/iri/spring/service/impl/UserServiceImpl.java
> +    private UserDao userDao;
done

2021-02-09 09:49 UTC, Sofasmile approved these changes

2021-02-09 12:55 UTC, merged